test: eliminate redundant code by eliminating determine_kernel_version
Both dracut and determine_kernel_version contains a similar code block
for determining linux kernel version.

Instead of duplicating code, let dracut compute the kernel version and
call lsinitrd on the generated initramfs to determine the kernel
version for testing as well.

remove unbound KVERSION variable.

diff --git a/test/run-qemu b/test/run-qemu
--- a/test/run-qemu
+++ b/test/run-qemu
@@ -8,33 +8,34 @@ ARCH="${ARCH-$(uname -m)}"
 QEMU_CPU="${QEMU_CPU:-max}"
 
 set_vmlinux_env() {
-    VMLINUZ=${VMLINUZ-"/lib/modules/${KVERSION}/vmlinuz"}
-    if ! [ -f "$VMLINUZ" ]; then
-        VMLINUZ="/lib/modules/${KVERSION}/vmlinux"
-    fi
-
-    if ! [ -f "$VMLINUZ" ]; then
-        [[ -f /etc/machine-id ]] && read -r MACHINE_ID < /etc/machine-id
-
-        if [[ ${MACHINE_ID-} ]] && { [[ -d /boot/${MACHINE_ID} ]] || [[ -L /boot/${MACHINE_ID} ]]; }; then
-            VMLINUZ="/boot/${MACHINE_ID}/$KVERSION/linux"
-        elif [ -f "/boot/vmlinuz-${KVERSION}" ]; then
-            VMLINUZ="/boot/vmlinuz-${KVERSION}"
-        elif [ -f "/boot/vmlinux-${KVERSION}" ]; then
-            VMLINUZ="/boot/vmlinux-${KVERSION}"
-        elif [ -f "/boot/kernel-${KVERSION}" ]; then
-            VMLINUZ="/boot/kernel-${KVERSION}"
-        elif [ -f "/boot/Image-${KVERSION}" ]; then
-            VMLINUZ="/boot/Image-${KVERSION}"
+    if [[ ${KVERSION-} ]]; then
+        VMLINUZ=${VMLINUZ-"/lib/modules/${KVERSION}/vmlinuz"}
+        if ! [ -f "$VMLINUZ" ]; then
+            VMLINUZ="/lib/modules/${KVERSION}/vmlinux"
         fi
-    fi
 
-    if ! [ -f "$VMLINUZ" ]; then
+        if ! [ -f "$VMLINUZ" ]; then
+            [[ -f /etc/machine-id ]] && read -r MACHINE_ID < /etc/machine-id
+
+            if [[ ${MACHINE_ID-} ]] && { [[ -d /boot/${MACHINE_ID} ]] || [[ -L /boot/${MACHINE_ID} ]]; }; then
+                VMLINUZ="/boot/${MACHINE_ID}/$KVERSION/linux"
+            elif [ -f "/boot/vmlinuz-${KVERSION}" ]; then
+                VMLINUZ="/boot/vmlinuz-${KVERSION}"
+            elif [ -f "/boot/vmlinux-${KVERSION}" ]; then
+                VMLINUZ="/boot/vmlinux-${KVERSION}"
+            elif [ -f "/boot/kernel-${KVERSION}" ]; then
+                VMLINUZ="/boot/kernel-${KVERSION}"
+            elif [ -f "/boot/Image-${KVERSION}" ]; then
+                VMLINUZ="/boot/Image-${KVERSION}"
+            fi
+        fi
+    else
         VMLINUZ=$(find /boot/vmlinuz-* -type f 2> /dev/null | tail -1)
+        ! [ -f "$VMLINUZ" ] && VMLINUZ=$(find /lib/modules/ -type f -name vmlinuz 2> /dev/null | tail -1)
     fi
 
     if ! [ -f "$VMLINUZ" ]; then
-        echo "Could not find a Linux kernel version $KVERSION to test with!" >&2
+        echo "Could not find a Linux kernel version to test with!" >&2
         echo "Please install linux." >&2
         exit 1
     fi
