refactor(test): move check_qemu_log to test-functions
Move `check_log` to `test/test-functions`, name it `check_qemu_log`, and
do not require to specify the success message (which will be the same
for all tests).

diff --git a/test/test-functions b/test/test-functions
--- a/test/test-functions
+++ b/test/test-functions
@@ -84,6 +84,16 @@ call_dracut() {
     "$DRACUT" "$@"
 }
 
+# Check QEMU logs for success marker
+check_qemu_log() {
+    local logfile="$1"
+
+    if ! grep -q "^All OK" "${logfile}"; then
+        echo >&2 "E: Message 'All OK' not found in QEMU log output '${logfile}'."
+        return 1
+    fi
+}
+
 # Log the start of a client test.
 client_test_start() {
     local test_name="$1"
